/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import newpackage.control;
import newpackage.StringUtil;
import newpackage.FormObject;

/**
 *
 * @author 王慧
 */
public class 登录 extends javax.swing.JFrame {

    /**
     * Creates new form 乘客登录
     */
      database database=new database();
    control co=new control();
    FormObject fo=new FormObject();
    public static passenger currentpassenger;
    public static admin_ currentadmin_;
    static String P_id;
    public 登录() {
       
    

    /**
     *
     */
    
        Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
//get(Object key)或get(Object key, Locale l)，返回Object，从默认值中返回一个对象。参数： key - 指定所需对象的 Object，l - 需要该对象的 Locale。
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
//put(Object key, Object value)，返回Object，在开发人员默认值中存储一个对象。此方法是 getDefaults().put(key, value) 的一个覆盖方法。此方法仅对开发人员默认值有效，对系统默认值和外观默认值无效。 简单地说就是把一个组件抽出来设置它的一些属性，比如设置全局组件的字体：
			}
		}
        initComponents();
        this.setTitle("登录");
        this.setLocationRelativeTo(null);
	this.jrb_passenger.setSelected(true);
         int windowWidth = this.getWidth(); //获得窗口宽
        int windowHeight = this.getHeight(); //获得窗口高
        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
        int screenWidth = screenSize.width; //获取屏幕的宽
        int screenHeight = screenSize.height; //获取屏幕的高
        this.setLocation(screenWidth / 2 - 605 / 2, screenHeight / 2 - 430 / 2);
        this.setExtendedState(JFrame.NORMAL);
        this.setSize(605,430);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrb_admin_ = new javax.swing.JRadioButton();
        jrb_passenger = new javax.swing.JRadioButton();
        userNameTxt = new javax.swing.JFormattedTextField();
        passwordTxt = new javax.swing.JPasswordField();
        jb_logOn = new javax.swing.JButton();
        jb_reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("黑体", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("火车票预订系统");

        jToggleButton1.setBackground(new java.awt.Color(1, 9, 41));
        jToggleButton1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("注册");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)), "欢迎登录", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("宋体", 1, 28), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("账号");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("密码");

        jrb_admin_.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jrb_admin_.setText("管理员");
        jrb_admin_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_admin_ActionPerformed(evt);
            }
        });

        jrb_passenger.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jrb_passenger.setText("乘客");
        jrb_passenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_passengerActionPerformed(evt);
            }
        });

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrb_admin_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrb_passenger)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_admin_)
                    .addComponent(jrb_passenger))
                .addGap(19, 19, 19))
        );

        jb_logOn.setBackground(new java.awt.Color(1, 9, 41));
        jb_logOn.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jb_logOn.setForeground(new java.awt.Color(255, 255, 255));
        jb_logOn.setText("登录");
        jb_logOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logOnActionPerformed(evt);
            }
        });

        jb_reset.setBackground(new java.awt.Color(0, 9, 41));
        jb_reset.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jb_reset.setForeground(new java.awt.Color(255, 255, 255));
        jb_reset.setText("重置");
        jb_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_logOn)
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jb_reset))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)))
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_logOn)
                    .addComponent(jToggleButton1)
                    .addComponent(jb_reset))
                .addGap(66, 66, 66))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/photos/火车1-1_中间有矩形框.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_admin_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_admin_ActionPerformed
        // TODO add your handling code here:
        if (jrb_admin_.isSelected()){
            jrb_passenger.setSelected(false);
        }
    }//GEN-LAST:event_jrb_admin_ActionPerformed

    private void jrb_passengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_passengerActionPerformed
        // TODO add your handling code here:
          if (jrb_passenger.isSelected()){
            jrb_admin_.setSelected(false);
          }
    }//GEN-LAST:event_jrb_passengerActionPerformed

    private void jb_logOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logOnActionPerformed
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
	    String password = new String(passwordTxt.getPassword());
		if (StringUtil.isEmpty(userName)) {
			fo.ShowInfo(this, "用户名不能为空!");
			return;
		}
		if (StringUtil.isEmpty(password)) {
			fo.ShowInfo(this, "密码不能为空!");
			return;
		}
		Connection con=null;
		if (this.jrb_passenger.isSelected()) {
			passenger passenger = new passenger();
                        passenger.setP_id(userName);
                        passenger.setP_password(password);
                       
			try {
				con=database.getCon();  
                               
				currentpassenger = co.Verifypassenger(con,passenger);
				if (currentpassenger != null) {
					this.dispose();
					new 主页和查询JFrame().setVisible(true);
				} else {
					JOptionPane.showMessageDialog(this, "登录失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "登录失败!");
			}finally{
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		} else if (this.jrb_admin_.isSelected()) {
			admin_ admin_ = new admin_();
                        admin_.setA_id(userName);
                        admin_.setA_password(password);
			try {
				con=database.getCon();
				currentadmin_ = co.Verifyadmin_(con, admin_);
				if (currentadmin_!= null) {
					this.dispose();
					new 管理员JFrame().setVisible(true);
				} else {
					JOptionPane.showMessageDialog(this, "登录失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "登录失败!");
			}finally{
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}     
        P_id = this.userNameTxt.getText();
    }//GEN-LAST:event_jb_logOnActionPerformed
                                      

                                            

                                       
    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resetActionPerformed
        // TODO add your handling code here:
        this.resetValue();
    }//GEN-LAST:event_jb_resetActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new 注册JFrame().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed
  private void resetValue() {
		this.userNameTxt.setText("");
		this.passwordTxt.setText("");
		this.jrb_passenger.setSelected(true);
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(登录.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(登录.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(登录.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(登录.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 登录().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jb_logOn;
    private javax.swing.JButton jb_reset;
    private javax.swing.JRadioButton jrb_admin_;
    private javax.swing.JRadioButton jrb_passenger;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JFormattedTextField userNameTxt;
    // End of variables declaration//GEN-END:variables

   
}
