/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
//import static com.sun.corba.se.impl.orbutil.CorbaResourceUtil.getText;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import newpackage.control;
import newpackage.StringUtil;

/**
 *
 * @author 王慧
 */
public class 老年人硬卧 extends javax.swing.JFrame {

    /**
     * Creates new form 老年人
     */
    database database=new database();
    control co=new control();
    FormObject fo=new FormObject();
    public static passenger currentpassenger;
    public static admin_ currentadmin_;
    String name=(String) 火车车次详情JFrame1.getname;
    String date=(String) 火车车次详情JFrame1.T_date;
    public 老年人硬卧() {
        initComponents();
        int windowWidth = this.getWidth(); //获得窗口宽
        int windowHeight = this.getHeight(); //获得窗口高
        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
        int screenWidth = screenSize.width; //获取屏幕的宽
        int screenHeight = screenSize.height; //获取屏幕的高
        this.setLocation(screenWidth / 2 - 605 / 2, screenHeight / 2 - 430 / 2);
        this.setExtendedState(JFrame.NORMAL);
        this.setSize(615,430);
        this.setTitle("老年人硬卧选择铺位");
    }
    static String hardtype;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(1, 9, 41));
        jButton1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("确认");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("黑体", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("老年人选座");

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("硬 卧");

        jRadioButton1.setBackground(new java.awt.Color(89, 94, 115));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton1.setText("上铺");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(89, 94, 115));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton2.setText("中铺");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(89, 94, 115));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton3.setText("下铺");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(jRadioButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(24, 24, 24)
                .addComponent(jRadioButton3)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 159, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 159, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 92, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 93, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/photos/火车1-2_矩形框2.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
try {
              if (jRadioButton1.isSelected()){
                  jRadioButton2.setSelected(false);
                  jRadioButton3.setSelected(false);
              }// TODO add your handling code here:
             // Connection con = null;
    
             // T_numberhard1(con,火车车次详情JFrame1.getname);
          } catch (Exception ex) {
              Logger.getLogger(老年人软卧.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
try {
              if (jRadioButton2.isSelected()){
                  jRadioButton1.setSelected(false);
                  jRadioButton3.setSelected(false);
              }// TODO add your handling code here:
             // Connection con = null;

              //T_numberhard2(con,火车车次详情JFrame1.getname);
          } catch (Exception ex) {
              Logger.getLogger(老年人软卧.class.getName()).log(Level.SEVERE, null, ex);
          }  
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
try {
              if (jRadioButton3.isSelected()){
                  jRadioButton2.setSelected(false);
                  jRadioButton1.setSelected(false);
              }// TODO add your handling code here:
             // Connection con = null;

              //T_numberhard3(con,火车车次详情JFrame1.getname);
          } catch (Exception ex) {
              Logger.getLogger(老年人软卧.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("传过来的车次为：");
        System.out.println(火车车次详情JFrame1.getname);
        
        System.out.println("name为："+name);
        if(jRadioButton1.isSelected()) {
    //try {
       // Connection con = null;

      //  T_numberhard1(con,火车车次详情JFrame1.getname);
       
    //} // TODO add your handling code here:
   // catch (Exception ex) {
       // Logger.getLogger(老年人硬卧.class.getName()).log(Level.SEVERE, null, ex);
   // }
    Connection con = null;      
    
    int selectionNum1 = 0;
    try {
        con = database.getCon();

        
        selectionNum1 = hard1(con);
        
    } catch (Exception ex) {
        Logger.getLogger(老年人软卧.class.getName()).log(Level.SEVERE, null, ex);
    }                   
                    if (selectionNum1 == 1 ) {
                        JOptionPane.showMessageDialog(this, "选座成功!");
                        
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "选座失败!");
                    }
            try {
                database.closeCon(con);
            } catch (Exception ex) {
                Logger.getLogger(老年人硬卧.class.getName()).log(Level.SEVERE, null, ex);
            }
}      
if(jRadioButton2.isSelected()) {
   
    Connection con = null;
    
    int selectionNum2 = 0;
    try {
         con = database.getCon();

        
        selectionNum2 = hard2(con);
    } catch (Exception ex) {
        Logger.getLogger(老年人软卧.class.getName()).log(Level.SEVERE, null, ex);
    }           
                    
                    if (selectionNum2 == 1) {
                        JOptionPane.showMessageDialog(this, "选座成功!");
                        
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "选座失败!");
                    }
            try {
                database.closeCon(con);
            } catch (Exception ex) {
                Logger.getLogger(老年人硬卧.class.getName()).log(Level.SEVERE, null, ex);
            }
}  
if(jRadioButton3.isSelected()) {
   
    Connection con = null;
    
    int selectionNum3 = 0;
    try {
         con = database.getCon();
 
        
        selectionNum3 = hard3(con);
    } catch (Exception ex) {
        Logger.getLogger(老年人硬卧.class.getName()).log(Level.SEVERE, null, ex);
    }
           
                   
                    if (selectionNum3 == 1 ) {
                        JOptionPane.showMessageDialog(this, "选座成功!");
                        
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "选座失败!");
                    }
            try {
                database.closeCon(con);
            } catch (Exception ex) {
                Logger.getLogger(老年人硬卧.class.getName()).log(Level.SEVERE, null, ex);
            }
}  this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(老年人硬卧.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(老年人硬卧.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(老年人硬卧.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(老年人硬卧.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 老年人硬卧().setVisible(true);
            }
        });
    }
    
    String currentP_id = 登录.currentpassenger.GetP_id();
    public int hard1(Connection con)throws Exception{
	String sql="update torder set hardtype = '上铺' where T_name = ? and P_id = ?" ;
		PreparedStatement pstmt=con.prepareStatement(sql);	        
                pstmt.setString(1,name);
                pstmt.setString(2,currentP_id);
               
                System.out.println(pstmt.toString());
		return pstmt.executeUpdate();	
	}
public int hard2(Connection con)throws Exception{
	String sql="update torder set hardtype = '中铺' where T_name = ? and P_id = ?" ;
		PreparedStatement pstmt=con.prepareStatement(sql);	        
                pstmt.setString(1,name);
                pstmt.setString(2,currentP_id);
                
                System.out.println(pstmt.toString());
		return pstmt.executeUpdate();	
	}
public int hard3(Connection con)throws Exception{
	String sql="update torder set hardtype = '下铺' where T_name = ? and P_id = ?" ;
		PreparedStatement pstmt=con.prepareStatement(sql);	        
                pstmt.setString(1,name);
                pstmt.setString(2,currentP_id);
               
                System.out.println(pstmt.toString());
		return pstmt.executeUpdate();	
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables

}
