/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;
import newpackage.control;
import newpackage.StringUtil;
import newpackage.FormObject;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import newpackage.database;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.awt.Font;
import java.sql.Date;

/**
 *
 * @author 王慧
 */
public class 退票JFrame extends javax.swing.JFrame {
        database database = new database();
	torder torder = new torder();
        hsorder hsorder = new hsorder();
        control co=new control();
	
	private String T_name;
       private String T_seattype;
        private String H_name;
       private String H_seattype;
        private String H_date;
        private String T_date;
        passenger passenger=new passenger();
    
    /**
     * Creates new form 订单详情JFrame
     */
    public 退票JFrame() {
        initComponents();
         int windowWidth = this.getWidth(); //获得窗口宽
        int windowHeight = this.getHeight(); //获得窗口高
        Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包
        Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸
        int screenWidth = screenSize.width; //获取屏幕的宽
        int screenHeight = screenSize.height; //获取屏幕的高
        this.setLocation(screenWidth / 2 - 1000 / 2, screenHeight / 2 - 520 / 2);
        this.setExtendedState(JFrame.NORMAL);
        this.setSize(1020,520);
       this.fillTable1(new torder());
        this.fillTable2(new hsorder());
        this.setTitle("退票");
    }
       
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tordertable = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hsordertable = new javax.swing.JTable();
        jb_selectionCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "火车", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("宋体", 1, 18), new java.awt.Color(1, 9, 41))); // NOI18N
        jPanel1.setOpaque(false);

        jScrollPane1.setForeground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setOpaque(false);

        tordertable.setBackground(new java.awt.Color(89, 94, 115));
        tordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "车次", "出发地", "到达地", "出发时间", "到达时间", "座位类型", "待付款", "出发日期"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tordertableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tordertable);

        jToggleButton1.setBackground(new java.awt.Color(1, 9, 41));
        jToggleButton1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(240, 240, 240));
        jToggleButton1.setText("退选");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(220, 220, 220))
        );

        jButton1.setBackground(new java.awt.Color(1, 9, 41));
        jButton1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("< 返回");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "高铁", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("宋体", 1, 18), new java.awt.Color(1, 9, 41))); // NOI18N
        jPanel2.setOpaque(false);

        jScrollPane2.setForeground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setOpaque(false);

        hsordertable.setBackground(new java.awt.Color(89, 94, 115));
        hsordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "车次", "出发地", "到达地", "出发时间", "到达时间", "座位类型", "待付款", "出发日期"
            }
        ));
        hsordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hsordertableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(hsordertable);
        if (hsordertable.getColumnModel().getColumnCount() > 0) {
            hsordertable.getColumnModel().getColumn(7).setResizable(false);
        }

        jb_selectionCancel.setBackground(new java.awt.Color(1, 9, 41));
        jb_selectionCancel.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jb_selectionCancel.setForeground(new java.awt.Color(240, 240, 240));
        jb_selectionCancel.setText("退选");
        jb_selectionCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_selectionCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(815, Short.MAX_VALUE)
                .addComponent(jb_selectionCancel)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jb_selectionCancel)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel3, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/photos/火车1_加蓝色边框830×380.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_selectionCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_selectionCancelActionPerformed
        // TODO add your handling code here:
  
    
      
    if (H_name=="" && H_seattype=="") {
		JOptionPane.showMessageDialog(this, "请选择要退选的车次！");
		return;
		}
		int m = JOptionPane.showConfirmDialog(this, "确认要退选这个车次吗?");
		if (m == 0) {
			Connection con = null;
			String currentP_id = 登录.currentpassenger.GetP_id();
			hsorder sc= new hsorder();
                        sc.setP_id(currentP_id);
                        sc.setH_seattype(H_seattype);
                        sc.setH_name(H_name);
                         sc.setH_date(H_date);
                        
			try {
				con = database.getCon();
                               
				int selectionNum = sc.SelectionCancel(con);
				int selectedNum = sc.H_numberAdd(con,H_name,H_seattype,H_date);
                                 System.out.println(selectionNum);
                                 System.out.println(selectedNum);
				if (selectionNum == 1 && selectedNum >= 1) {
					JOptionPane.showMessageDialog(this, "退选成功!");
					this.fillTable2(new hsorder());
				} else {
					JOptionPane.showMessageDialog(this, "退选失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "退选失败!");
			} finally {
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
    }    
    
    
    }//GEN-LAST:event_jb_selectionCancelActionPerformed

    private void tordertableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tordertableMousePressed
        // TODO add your handling code here:
        int row = tordertable.getSelectedRow();
	 T_name= (String) tordertable.getValueAt(row, 0);
           T_date = (String) tordertable.getValueAt(row, 7);
         T_seattype= (String) tordertable.getValueAt(row, 5);
    }//GEN-LAST:event_tordertableMousePressed

    private void hsordertableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hsordertableMousePressed
        // TODO add your handling code here:
        int row = hsordertable.getSelectedRow();
	 H_name= (String) hsordertable.getValueAt(row, 0);
          H_date = (String) hsordertable.getValueAt(row, 7);
         H_seattype= (String) hsordertable.getValueAt(row, 5);
    }//GEN-LAST:event_hsordertableMousePressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         if (T_name=="" && T_seattype=="") {
		JOptionPane.showMessageDialog(this, "请选择要退选的车次！");
		return;
		}
		int n = JOptionPane.showConfirmDialog(this, "确认要退选这个车次吗?");
		if (n == 0) {
			Connection con = null;
			String currentP_id = 登录.currentpassenger.GetP_id();
			torder sc= new torder();
                        sc.setT_name(T_name);
                        sc.setT_date(T_date);
                        sc.setT_seattype(T_seattype);
                        sc.setP_id(currentP_id);
			try {
				con = database.getCon();
				int selectionNum = sc.SelectionCancel(con);
				int selectedNum = sc.T_numberAdd(con,T_name,T_seattype,T_date);
				if (selectionNum == 1 && selectedNum == 1) {
					JOptionPane.showMessageDialog(this, "退选成功!");
					this.fillTable1(new torder());
				} else {
					JOptionPane.showMessageDialog(this, "退选失败!");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "退选失败!");
			} finally {
				try {
					database.closeCon(con);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
    }  
       
    
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
new 乘客个人中心JFrame().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
        private void fillTable1(torder torder) {
		DefaultTableModel dtm = (DefaultTableModel) tordertable.getModel();
		dtm.setRowCount(0);
		Connection con = null;
                torder sc=new torder();
                
		String P_id= 登录.currentpassenger.GetP_id();
                passenger.setP_id(P_id);
                System.out.println(passenger.GetP_id());
		try {
			con = database.getCon();
			ResultSet rs = sc.PassengerList(con, passenger);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString(1));
				v.add(rs.getString(2));
				v.add(rs.getString(3));
				v.add(rs.getString(4));
                                v.add(rs.getString(5));
				v.add(rs.getString(6));
				v.add(rs.getString(7));
				 v.add(rs.getString(8));
                             
				dtm.addRow(v);

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				database.closeCon(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
        
           private void fillTable2(hsorder hsorder) {
		DefaultTableModel dtm = (DefaultTableModel) hsordertable.getModel();
		dtm.setRowCount(0);
		Connection con = null;
                hsorder sc=new hsorder();
                
		String P_id = 登录.currentpassenger.GetP_id();
                passenger.setP_id(P_id);
                System.out.println(passenger.GetP_id());
		try {
			con = database.getCon();
			ResultSet rs = sc.PassengerList(con, passenger);
			while (rs.next()) {
				Vector v = new Vector();
				v.add(rs.getString(1));
				v.add(rs.getString(2));
				v.add(rs.getString(3));
				v.add(rs.getString(4));
                                v.add(rs.getString(5));
				
				v.add(rs.getString(6));
				v.add(rs.getString(7));
                                v.add(rs.getString(8));
                                
				dtm.addRow(v);

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				database.closeCon(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
     
                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(退票JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(退票JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(退票JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(退票JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  new 退票JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable hsordertable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jb_selectionCancel;
    private javax.swing.JTable tordertable;
    // End of variables declaration//GEN-END:variables

   

  
}
